@isTest
public class DeleteQATesting_Opsera123456 {
private Integer num;
    
    @isTest
   public static void helloMethod() {

        System.debug('Change Hello QA Testing Basic Pipeline testing UAT Github webhook 14/03/2023 PR Approved');
    
        System.debug('Change Hello QA Testing Basic Pipeline testing UAT Github webhook 14/03/2023 PR Approved');

    }
    
    public static testMethod void testNewMethod() {
        System.debug('Change Hello DemoApex10 testing 1234 Basic ');
    }
}